Controllers/TouristsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TourBase_Stage_1_2;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Http;
using System.IO;
using ClosedXML.Excel;

namespace TourBase_Stage_1_2.Controllers
{
    public class TouristsController : Controller
    {
        //bool Contains(string s, string value)
        //{
        //    if(s.Length > value.Length)
        //        return false;
        //    int dist = (value.Length - s.Length);
        //    string val;
        //    for (int i = 0; i < dist; i++)
        //    {
        //        for (int j = 0; j < s.Length)
        //    }
        //    return false;
        //}

        private readonly TourBaseContext _context;

        public TouristsController(TourBaseContext context)
        {
            _context = context;
        }

        // GET: Tourists
        public async Task<IActionResult> Index()
        {
            return View(await _context.Tourists.ToListAsync());
        }

        // GET: Tourists/Details/5
        public async Task<IActionResult> Details(int? id, string? name)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tourist = await _context.Tourists
                .FirstOrDefaultAsync(m => m.TouristId == id);
            if (tourist == null)
            {
                return NotFound();
            }

            //return View(tourist);
            return RedirectToAction("Index", "Vouchers", new { id = tourist.TouristId, name = tourist.TouristName });
        }

        // GET: Tourists/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tourists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TouristId,TouristName,BirthDate,EmailAdress")] Tourist tourist)
        {
            if (string.IsNullOrEmpty(tourist.EmailAdress))
            {
                ModelState.AddModelError("EmailAdress", "Це поле повинно бути заповнене");
            }
            else
            {
                Regex regex = new Regex(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", RegexOptions.CultureInvariant | RegexOptions.Singleline);
                bool isValidEmail = regex.IsMatch(tourist.EmailAdress);
                if (!isValidEmail)
                {
                    ModelState.AddModelError("EmailAdress", "Невірний запис e-mail адреси");
                }
            }

            DateTime t = Convert.ToDateTime("01.01.1920");
            if (tourist.BirthDate < t)
            {
                ModelState.AddModelError("BirthDate", "Некоректний вік");
            }

            if (ModelState.IsValid)
            {
                _context.Add(tourist);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tourist);
        }

        // GET: Tourists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tourist = await _context.Tourists.FindAsync(id);
            if (tourist == null)
            {
                return NotFound();
            }
            return View(tourist);
        }

        // POST: Tourists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TouristId,TouristName,BirthDate,EmailAdress")] Tourist tourist)
        {
            if (string.IsNullOrEmpty(tourist.EmailAdress))
            {
                ModelState.AddModelError("EmailAdress", "Це поле повинно бути заповнене");
            }
            else
            {
                Regex regex = new Regex(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", RegexOptions.CultureInvariant | RegexOptions.Singleline);
                bool isValidEmail = regex.IsMatch(tourist.EmailAdress);
                if (!isValidEmail)
                {
                    ModelState.AddModelError("EmailAdress", "Невірний запис e-mail адреси");
                }
            }

            if (id != tourist.TouristId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tourist);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TouristExists(tourist.TouristId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tourist);
        }

        // GET: Tourists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tourist = await _context.Tourists
                .FirstOrDefaultAsync(m => m.TouristId == id);
            if (tourist == null)
            {
                return NotFound();
            }

            return View(tourist);
        }

        // POST: Tourists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var tourist = await _context.Tourists.FindAsync(id);
        //    _context.Tourists.Remove(tourist);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tourBaseContext = _context.Vouchers.Where(v => v.TouristId == id).Include(v => v.Tour).Include(v => v.Tourist);
            var cont = tourBaseContext.ToList();
            if (cont.Count == 0)
            {
                var tourist = await _context.Tourists.FindAsync(id);
                _context.Tourists.Remove(tourist);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else 
            {
                return RedirectToAction("TouristsDeleteError", "Home");
            }
        }

        // GET: Tourists/Delete/5
        public async Task<IActionResult> DeleteKask(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tourist = await _context.Tourists
                .FirstOrDefaultAsync(m => m.TouristId == id);
            if (tourist == null)
            {
                return NotFound();
            }

            return View(tourist);
        }

        // POST: Tourists/Delete/5
        [HttpPost, ActionName("DeleteKask")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DeleteKaskConfirmed(int id)
        {
            var tourBaseContext = _context.Vouchers.Where(v => v.TouristId == id).Include(v => v.Tour).Include(v => v.Tourist);
            var cont = tourBaseContext.ToList();
            var tourist = await _context.Tourists.FindAsync(id);
            _context.Tourists.Remove(tourist);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TouristExists(int id)
        {
            return _context.Tourists.Any(e => e.TouristId == id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Import(IFormFile fileExcel)
        {
            if (ModelState.IsValid)
            {
                if (fileExcel != null)
                {
                    using (var stream = new FileStream(fileExcel.FileName, FileMode.Create))
                    {
                        var tourBaseContextTourist = _context.Tourists.ToList();
                        foreach (var t in tourBaseContextTourist)
                        {
                            await DeleteKask(t.TouristId);
                        }
                        await fileExcel.CopyToAsync(stream);
                        using (XLWorkbook workBook = new XLWorkbook(stream, XLEventTracking.Disabled))
                        {
                            //перегляд усіх листів (в даному випадку категорій)
                            foreach (IXLWorksheet worksheet in workBook.Worksheets)
                            {
                                //worksheet.Name - назва категорії. Пробуємо знайти в БД, якщо відсутня, то створюємо нову
                                Tourist newcat;
                                var c = (from cat in _context.Tourists
                                         where cat.TouristName.Contains(worksheet.Name)
                                         select cat).ToList();
                                if (c.Count > 0)
                                {
                                    newcat = c[0];
                                }
                                else
                                {

Views/Tourists/Create.cshtml
@model TourBase_Stage_1_2.Tourist

@{
    ViewData["Title"] = "Створити нового туриста";
}

<h1>Створити нового туриста</h1>

<h4>Турист</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TouristName" class="control-label"></label>
                <input asp-for="TouristName" class="form-control" />
                <span asp-validation-for="TouristName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailAdress" class="control-label"></label>
                <input asp-for="EmailAdress" class="form-control" />
                <span asp-validation-for="EmailAdress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Створити" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад до таблиці туристів</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Tourists/Delete.cshtml
@model TourBase_Stage_1_2.Tourist

@{
    ViewData["Title"] = "Видалення туриста";
}

<h1>Видалення туриста</h1>

<h3>Ви впевненні, що хочете видалити цього туриста?</h3>
<div>
    <h4>Турист</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TouristName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TouristName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailAdress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailAdress)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TouristId" />
        <input type="submit" value="Видалити" class="btn btn-danger" /> |
        <a asp-action="Index">Назад до таблиці туристів</a>
    </form>
</div>

Views/Tourists/DeleteKask.cshtml
@model TourBase_Stage_1_2.Tourist

@{
    ViewData["Title"] = "Каскадне видалення туриста";
}

<h1>Каскадне видалення туриста</h1>

<h3>Ви впевненні, що хочете видалити цього туриста?</h3>
<div>
    <h4>Турист</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TouristName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TouristName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EmailAdress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EmailAdress)
        </dd>
    </dl>

    <form asp-action="DeleteKask">
        <input type="hidden" asp-for="TouristId" />
        <input type="submit" value="Каскадно видалити" class="btn btn-danger" /> |
        <a asp-action="Index">Назад до таблиці туристів</a>
    </form>
</div>

Views/Tourists/Details.cshtml
@model TourBase_Stage_1_2.Tourist

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Tourist</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TouristName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TouristName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailAdress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailAdress)
        </dd>
    </dl>
</div>
<div>
    @*<a asp-action="Edit" asp-route-id="@Model.TouristId">Edit</a> |*@
    <a asp-action="Index">Back to List</a>
</div>

Views/Tourists/Edit.cshtml
@model TourBase_Stage_1_2.Tourist

@{
    ViewData["Title"] = "Виправити туриста";
}

<h1>Виправити туриста</h1>

<h4>Турист</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TouristId" />
            <div class="form-group">
                <label asp-for="TouristName" class="control-label"></label>
                <input asp-for="TouristName" class="form-control" />
                <span asp-validation-for="TouristName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailAdress" class="control-label"></label>
                <input asp-for="EmailAdress" class="form-control" />
                <span asp-validation-for="EmailAdress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Зберегти" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад до таблиці турів</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Tourists/Index.cshtml
@model IEnumerable<TourBase_Stage_1_2.Tourist>

@{
    ViewData["Title"] = "Туристи";
}

<h1>Туристи</h1>

<p>
    <a asp-action="Create">Створити нового туриста</a>
</p>

<div>
    <h3>Оберіть exel-файл для заватаження</h3>
    @using (Html.BeginForm("Import", "Tourists", FormMethod.Post, new { enctype = "multipart/form-data", id = "frm-excel" }))
    {
        <div>
            Завантажте Excel-файл:
            <input type="file" name="fileExcel" id="fileExcel" />
            <div>
                <input type="submit" value="Завантажити" />
            </div>
        </div>
    }
</div>

<div>
    <h3>Завантаження інформації в файл</h3>
    <a asp-action="Export">Завантажити</a>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TouristName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BirthDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailAdress)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TouristName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BirthDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmailAdress)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.TouristId">Виправити туриста</a> |
                    <a asp-action="Details" asp-route-id="@item.TouristId">Подивитися ваучери даного туриста</a> |
                    <a asp-action="Delete" asp-route-id="@item.TouristId">Видалити туриста</a> |
                    <a asp-action="DeleteKask" asp-route-id="@item.TouristId">Каскадно видалити туриста</a>
                </td>
            </tr>
        }
    </tbody>
</table>